[project]
name = "rag-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.0.20",
    "fastapi>=0.116.1",
    "huggingface-hub>=0.34.4",
    "langchain-community>=0.3.27",
    "langchain-core>=0.3.74",
    "langchain>=0.3.27",
    "pymupdf>=1.26.3",
    "sentence-transformers>=5.1.0",
    "uvicorn>=0.35.0",
]
